const https = require('https');
const fs = require('fs');
const path = require('path');

const OUTPUT_FILE = path.join(__dirname, '../../src/posts/' + new Date().toISOString().split('T')[0] + '-tech-radar.json');

// Helper: Simple fetch wrapper
function fetchJson(url) {
    return new Promise((resolve, reject) => {
        https.get(url, { headers: { 'User-Agent': 'Alex-Yalin-Bot' } }, (res) => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                try {
                    resolve(JSON.parse(data));
                } catch (e) {
                    reject(e);
                }
            });
        }).on('error', reject);
    });
}

async function getHackerNewsTop() {
    try {
        // Get top 50 IDs
        const topIds = await fetchJson('https://hacker-news.firebaseio.com/v0/topstories.json');
        const top5 = topIds.slice(0, 5); // Only top 5
        
        const stories = await Promise.all(top5.map(id => 
            fetchJson(`https://hacker-news.firebaseio.com/v0/item/${id}.json`)
        ));

        return stories.map(s => `<li><a href="${s.url}" target="_blank"><strong>${s.title}</strong></a> (${s.score} pts)</li>`).join('');
    } catch (e) {
        return "<li>Veri çekilemedi (Hacker News).</li>";
    }
}

async function generateRadar() {
    console.log("Scanning Hacker News...");
    const hnContent = await getHackerNewsTop();
    
    const today = new Date().toISOString().split('T')[0];
    
    const postContent = {
        title: `Tech Radar: ${today}`,
        date: today,
        category: "radar",
        content_en: `
            <p><strong>Daily Signal Scan:</strong> A curated look at what the tech world is discussing right now. No noise, just the top signals.</p>
            <h3>Hacker News (Top 5)</h3>
            <ul>${hnContent}</ul>
            <p><em>This report was automatically generated by Alex Yalın's Radar module.</em></p>
        `,
        content_tr: `
            <h3>Teknoloji Radarı: ${today}</h3>
            <p><strong>Günlük Sinyal Taraması:</strong> Teknoloji dünyasının şu an ne konuştuğuna dair küratörlü bir bakış. Gürültü yok, sadece en tepedeki sinyaller.</p>
            <h4>Hacker News (İlk 5)</h4>
            <ul>${hnContent}</ul>
            <p><em>Bu rapor Alex Yalın'ın Radar modülü tarafından otomatik olarak oluşturulmuştur.</em></p>
        `
    };

    fs.writeFileSync(OUTPUT_FILE, JSON.stringify(postContent, null, 4));
    console.log(`Radar generated: ${OUTPUT_FILE}`);
}

generateRadar();